### ISSUE TITLE
error starting bot

### ISSUE THREAD

**Issue by Yuinoshi** [Ratismal/UNO#28]
help me to fix this

```
PS C:\UNO-master\UNO-master> node index.js
C:\UNO-master\UNO-master\src\Spawner\index.js:11
    this.max = config.shards.max;
                             ^

TypeError: Cannot read property 'max' of undefined
    at new Spawner (C:\UNO-master\UNO-master\src\Spawner\index.js:11:30)
    at new Client (C:\UNO-master\UNO-master\src\index.js:8:20)
    at Object.<anonymous> (C:\UNO-master\UNO-master\src\index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\UNO-master\UNO-master\index.js:1:1)
```

**Comment by legouju** [comment]
same having this issue berh

also, how should the config.json be laid out xd

**Comment by Ratismal** [comment]
Please refer to the section about selfhosting in the readme.

## Selfhosting
You may selfhost (AKA run your own instance of) this bot under the following circumstances:
- Your instance (referred to as a "clone") must be private.
  - As such, your clone must not be listed on any sort of public bot listing.
- You understand that no support will be provided to aid you in self-hosting.
- You agree to not submit any issues, features, or pull requests related to bugs exclusively related to self-hosting.

**Comment by Yuinoshi** [comment]
oh okay
